<?php

namespace App\Service\Validator\Classes;

use App\Service\Validator\Interfaces\PassValidatorStrategyInterface;
use Symfony\Component\DependencyInjection\Attribute\AutoconfigureTag;

/**
 * Class implementing PassValidatorStrategyInterface for password validation.
 */
#[AutoconfigureTag('validator.strategy')]
class EasyPasswordStrategy implements PassValidatorStrategyInterface
{

    private array $weakPasswords = [
        'cities' => ["marseille", "paris", "lyon", "toulouse", "nice", "nantes", "bordeaux", "lille", "strasbourg", "montpellier", "avignon", "dijon", "grenoble", "rouen", "amiens", "perpignan", "nancy", "reims", "caen", "metz", "lorient", "rennes", "bayonne", "ajaccio", "bastia", "cannes", "antibes", "arles", "saintetienne", "villeurbanne", "aubervilliers", "pantin", "nanterre", "clermont", "tours", "orléans", "annecy", "angers", "poitiers", "le_havre", "mulhouse", "troyes", "colmar", "boulogne", "dunkerque", "valenciennes", "sedan", "versailles", "saintdenis", "albi", "alençon", "meaux", "limoges", "laval", "chalon", "besançon", "chantilly", "agen", "alès", "belfort", "béziers", "istres", "tarbes", "quimper", "blois", "evreux", "montluçon", "niort", "vannes", "draguignan", "sète", "martigues", "lunéville", "forbach", "bar_le_duc", "charleville", "chambéry", "thionville", "annemasse", "fontenay", "nogent", "courbevoie", "clichy", "levallois", "rosny", "montrouge", "ivry", "argenteuil", "villepinte", "montigny", "garges", "chelles", "noisy"],
        'departments' => ["13marseille", "75paris", "33bordeaux", "69lyon", "31toulouse", "06nice", "44nantes", "59lille", "67strasbourg", "34montpellier", "76rouen", "83toulon", "38grenoble", "21dijon", "51reims", "54nancy", "29brest", "30nîmes", "26valence", "22saintbrieuc", "35rennes", "56vannes", "68mulhouse", "88épinal", "64pau", "40montde", "11carcassonne", "09foix", "32auch", "02laon", "78versailles", "92nanterre", "94creteil", "93bobigny", "77melun", "95pontoise", "91evry", "90belfort", "89auxerre", "86poitiers", "80amiens", "79niort", "71mâcon", "70vesoul", "58nevers", "53laval", "52chaumont", "50saintlo", "49angers", "48mende", "47agen", "46cahors", "45orléans", "42saintetienne", "41blois", "40dax", "39lons", "38grenoble", "37tours", "36châteauroux", "35rennes", "34montpellier", "33bordeaux", "32auch", "31toulouse", "30nîmes", "29quimper", "28chartres", "27evreux", "26valence", "25besançon", "24perigueux", "23guéret", "22saintbrieuc", "21dijon", "20ajaccio", "19tulle", "18bourges", "17larochelle", "16angoulême", "15aurillac", "14caen", "13marseille", "12rodez", "11carcassonne", "10troyes", "09foix", "08charleville", "07privas", "06nice", "05gap", "04digne", "03moulins", "02laon", "01bourg"],
        'birthdates' => ["1980", "1990", "2000", "01011990", "25071985", "31121999", "14022000", "1975", "1985", "1995", "01011980", "15081995", "22062000", "1234567890", "01012000", "31122010", "24092015", "1992", "1988", "01011970", "04071985", "30122000", "1993", "1986", "2010", "01012010", "1997", "2015", "1970", "2005", "1972", "2012", "1991", "1987", "1983", "1984", "01011960", "25031990", "10101990", "15122000", "1994", "2001", "02021980", "23031980", "2007", "04042010", "18051985", "1979", "1978", "1973", "02022000", "2018", "01012018", "01011965", "2020", "1989", "1981", "1982", "03032000", "1974", "1965", "01011955", "01011950", "30121960", "1986", "2022", "01012022", "15022022", "15022000", "01012025", "2025", "2023", "2024", "01012024", "31122024", "01012026", "1971", "01011972", "01012027", "01012028", "01012029", "01012030", "1977", "2026", "01012026", "2027", "01012028", "01012029", "01012030", "2028", "01012029", "01012030", "01012031", "2029", "2030", "01012031"],
        'names' => ["julien", "marie", "lucas", "emma", "sophie", "camille", "paul", "clara", "léa", "nathan", "hugo", "alice", "nicolas", "manon", "thomas", "antoine", "laura", "gabriel", "louis", "charlotte", "maxime", "élise", "sarah", "juliette", "louise", "victor", "alexandre", "élisa", "quentin", "pierre", "arthur", "enzo", "léonie", "théo", "eva", "chloé", "valentin", "anaïs", "élodie", "clément", "margaux", "mathieu", "léon", "emma", "lucie", "adam", "lila", "julie", "adèle", "léandre", "léopold", "thibaut", "éva", "mélanie", "aurélien", "damien", "elisa", "sacha", "amelia", "olivia", "lucille", "erwan", "dorian", "léana", "nina", "thibault", "clémence", "loïc", "maxime", "océane", "ambre", "angélique", "mathias", "raphaël", "élie", "adrian", "eloise", "aurelie", "caroline", "fabien", "florian", "romane", "tiffany", "lena", "mael", "rosalie", "antonin", "gaspard", "lou"],
        'pets' => ["rex", "minou", "doudou", "choupette", "loulou", "titi", "médor", "filou", "gribouille", "snoopy", "poupou", "nala", "simba", "coco", "mimi", "léo", "poupi", "caramel", "biscuit", "câlin", "fluffy", "cookie", "shadow", "angel", "tiger", "oscar", "bella", "rosie", "jack", "jasper", "lucky", "charlie", "max", "rocky", "duke", "maggie", "toby", "bailey", "chloe", "daisy", "ginger", "milo", "zoe", "honey", "pepper", "poppy", "scout", "sophie", "louie", "teddy", "copper", "gracie", "buster", "hunter", "koda", "jax", "luna", "bear", "buddy", "blue", "cody", "piper", "olive", "ruby", "simba", "ollie", "otis", "lady", "dexter", "leo", "shadow", "bandit", "charlie", "murphy", "hank", "moose", "marley", "whiskey", "millie", "nova", "ellie", "paisley", "finley", "cleo", "midnight", "ranger", "rufus", "smokey", "stella", "rebel", "phoenix", "sugar"],
        'days_and_months' => ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche", "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre", "lundi01", "lundi02", "mardi03", "jeudi12", "vendredi24", "dimanche31", "janvier2022", "février2022", "mars2022", "avril2022", "mai2022", "juin2022", "juillet2022", "août2022", "septembre2022", "octobre2022", "novembre2022", "décembre2022", "lundi2022", "mardi2022", "mercredi2022", "jeudi2022", "vendredi2022", "samedi2022", "dimanche2022", "lundi2023", "mardi2023", "mercredi2023", "jeudi2023", "vendredi2023", "samedi2023", "dimanche2023", "janvier2023", "février2023", "mars2023", "avril2023", "mai2023", "juin2023", "juillet2023", "août2023", "septembre2023", "octobre2023", "novembre2023", "décembre2023", "janvier2024", "février2024", "mars2024", "avril2024", "mai2024", "juin2024", "juillet2024", "août2024", "septembre2024", "octobre2024", "novembre2024", "décembre2024", "lundi2024", "mardi2024", "mercredi2024", "jeudi2024", "vendredi2024", "samedi2024", "dimanche2024"],
        'keyboard_patterns' => ["azerty", "qwerty", "123456", "1234", "0000", "1111", "123123", "654321", "asdfgh", "zxcvbn", "qwertz", "poiuy", "098765", "1q2w3e", "password", "pass123", "admin", "123qwe", "qazwsx", "asdf123", "admin123", "000000", "1qaz2wsx", "112233", "qwertyuiop", "asdfghjkl", "zxcvbnm", "admin1", "password1", "12345", "54321", "pass", "qwe123", "test", "hello", "letmein", "sunshine", "iloveyou", "welcome", "monkey", "football", "whatever", "q1w2e3", "abc123", "passw0rd", "1q2w3e4", "admin2", "admin1234", "pass4321", "mypassword", "super123", "test123", "adminadmin", "passadmin", "testadmin", "root", "master", "test1234", "mypwd", "superuser", "user123", "test12345", "admin987", "adminpass", "secure123", "secure1", "pass111", "pass2023", "testpwd", "default", "qwert123", "hello123", "user1", "hello1", "qwert12345", "password2", "mypassword123", "qwert456", "123test", "testtest", "testuser", "root123", "pass12345", "passpass", "testadmin1", "adminpassword", "mypassword1", "testpwd123", "passw123", "admin123456", "1qazwsx", "q1w2e3r4t5"],
        'hobbies' => ["foot", "rugby", "tennis", "basket", "danse", "musique", "peinture", "lecture", "écriture", "cuisine", "pâtisserie", "dessin", "guitare", "piano", "chant", "cinéma", "théâtre", "jardinage", "pêche", "chasse", "natation", "plongée", "course", "yoga", "fitness", "cyclisme", "vélo", "randonnée", "surf", "ski", "snowboard", "escalade", "boxe", "karaté", "kungfu", "judo", "ballet", "hiphop", "streetdance", "graffiti", "modélisme", "drone", "robotique", "programmation", "gaming", "esport", "streaming", "vlogging", "podcasting", "numismatique", "philatélie", "collection", "lego", "puzzle", "scrabble", "échecs", "jeuxvidéo", "ps5", "xbox", "nintendo", "switch", "pcgaming", "retrogaming", "modélisme", "maquette", "train", "aviation", "café", "thé", "chocolat", "glace", "vin", "fromage", "bière", "cocktail", "voiture", "moto", "camping", "voyage", "randonnée", "aventure", "exploration", "astronomie", "astrologie", "méditation", "écologie", "environnement", "animaux", "nature", "science", "technologie", "informatique", "robotique", "histoire", "géographie", "langues"],
        'celebrities' => ["zidane", "messi", "ronaldo", "mbappe", "beyonce", "madonna", "drake", "rihanna", "adele", "ed sheeran", "justin bieber", "taylor swift", "lady gaga", "eminem", "jay z", "kanye west", "bruno mars", "coldplay", "the weeknd", "shakira", "britney spears", "billie eilish", "dua lipa", "shawn mendes", "ariana grande", "doja cat", "olivia rodrigo", "kylie jenner", "kim kardashian", "david beckham", "lebron james", "roger federer", "serena williams", "tiger woods", "novak djokovic", "usain bolt", "michael jordan", "cristiano", "george clooney", "brad pitt", "angelina jolie", "johnny depp", "leonardo dicaprio", "scarlett johansson", "robert downey jr", "chris hemsworth", "tom cruise", "will smith", "morgan freeman", "dwayne johnson", "vin diesel", "charlize theron", "keanu reeves", "tom holland", "zendaya", "chris evans", "ryan reynolds", "ryan gosling", "emma watson", "daniel radcliffe", "rupert grint", "alan rickman", "helena bonham carter", "meryl streep", "julia roberts", "anne hathaway", "kate winslet", "sandra bullock", "hugh jackman", "patrick stewart", "ian mckellen", "benedict cumberbatch", "elijah wood", "ian somerhalder", "nina dobrev", "paul wesley", "kat graham", "candice king", "joseph morgan", "danielle campbell", "charles michael davis", "claire holt", "matthew davis", "chris pratt", "zoe saldana", "vin diesel", "bradley cooper", "karen gillan", "pom klementieff", "dave bautista", "elizabeth olsen", "tom hiddleston", "sebastian stan"],
        'events' => ["noel", "halloween", "pâques", "saintvalentin", "nouvelan", "mariage", "anniversaire", "vacances", "fêtedesmères", "fêtedespères", "rentrée", "festival", "concert", "carnaval", "réveillon", "baptême", "communion", "confirmation", "crémaillère", "adoption", "naissance", "déménagement", "retraite", "promotion", "diplôme", "job", "emploi", "stage", "festivaldécannes", "tourdefrance", "rolandgarros", "jeuxolympiques", "championnatsdumonde", "coupeeurope", "coupeafrique", "coupeamerique", "superbowl", "nba", "championsleague", "euro", "mondial", "fêteforaine", "salon", "exposition", "colloque", "conférence", "séminaire", "atelier", "formation", "formationcontinue", "stageprofessionnel", "stageécole", "réunion", "télétravail", "webinaire", "anniversaire50ans", "anniversaire30ans", "anniversaire20ans", "graduation", "noel2023", "halloween2024", "pâques2023", "mariage2025", "fête2023", "naissance2024", "événement2023", "vacances2024", "rentrée2023", "promotion2023", "retraite2024", "championnats2024", "rolandgarros2024", "tourdefrance2023", "jeuxolympiques2024", "coupeeurope2024", "superbowl2024", "nba2023", "champions2023", "euro2024", "mondial2023", "fêteforaine2023", "salon2023", "webinaire2023", "atelier2023", "formation2023", "stagedébutant", "stageavancé", "stagemanager", "stagedirection"],
        'films_and_series' => ["starwars", "harrypotter", "gameofthrones", "breakingbad", "friends", "naruto", "bleach", "dbz", "batman", "spiderman", "avengers", "ironman", "thor", "joker", "strangerthings", "matrix", "inception", "shrek", "minions", "luca", "frozen", "moana", "coco", "encanto", "thelionking", "beautyandthebeast", "aladdin", "mulan", "findingnemo", "toystory", "cars", "up", "zootopia", "brave", "tangled", "ratatouille", "monstersinc", "walle", "soul", "lightyear", "turningred", "insideout", "onward", "theincredibles", "thegooddinosaur", "bambi", "dumbo", "peterpan", "ladyandthetramp", "cinderella", "sleepingbeauty", "snowwhite", "pinocchio", "101dalmatians", "thejunglebook", "thearistocats", "robinhood", "thefoxandthehound", "hercules", "tarzan", "pocahontas", "hunchbackofnotredame", "atlantis", "treasureplanet", "brotherbear", "homeonthe_range", "meettherobinsons", "bolt", "princessthefrog", "ralph", "wreckitralph", "ralphbreakstheinternet", "bighero6", "spidermanintothespiderverse", "milesmorales", "venom", "morbius", "nope", "getout", "us", "parasite", "spiritedaway", "howlsmovingcastle", "myneighbortotoro", "princessmononoke", "ponyo", "kikisdeliveryservice", "castleinthesky", "nausicaa", "thewindrises", "whisperoftheheart", "earthsea", "cats", "lesmiserables", "hamilton", "wicked", "phantomoftheopera", "westside_story", "chicago"],
        'geographical_references' => ["Provence", "Alpes", "Pyrénées", "Bretagne", "Normandie", "Rhône", "Garonne", "Seine", "Loire", "Jura", "Vosges", "Vendée", "Sologne", "Camargue", "Riviera", "MontBlanc", "Everest", "Kilimanjaro", "Sahara", "Amazonie", "Andes", "Himalaya", "Rockies", "Appalaches", "Cascades", "Atlas", "Carpates", "Ural", "Pamirs", "Alaska", "Caucase", "Tibet", "Patagonie", "Tundra", "Taïga", "Steppes", "Savane", "Désert", "Océan", "Méditerranée", "Atlantique", "Pacifique", "Arctique", "Antarctique", "Caraïbes", "Adriatique", "Baltique", "Indien", "GolfePersique", "MerRouge", "MerNoire", "MerJaune", "MerCaspienne", "Baïkal", "Amazonie", "Nil", "Mississippi", "Yangtsé", "Mékong", "Gange", "Euphrate", "Tigre", "Danube", "Rhin", "Volga", "Thames", "Seine", "Hudson", "Yukon", "Zambèze", "Victoria", "Titicaca", "Baïkal", "Tanganyika", "Supérieur", "Michigan", "Huron", "Ontario", "Erie", "Baïkal", "Crète", "Sicile", "Corse", "Sardaigne", "Baléares", "Cyclades", "Hawaii", "Galapagos", "Maldives", "BoraBora", "Fidji", "Philippines", "Canaries", "Madeira", "Tasmanie", "Bornéo", "Sumatra", "Java", "NouvelleGuinée"],
        'brands_and_companies' => ["flixbus", "volvo", "fluxel", "google", "amazon", "facebook", "apple", "microsoft", "netflix", "nike", "adidas", "samsung", "huawei", "tesla", "bmw", "volvo", "peugeot", "renault", "citroen", "sony", "canon", "ikea", "starbucks", "coca", "pepsi", "nestle", "danone", "unilever", "puma", "reebok", "newbalance", "asics", "underarmour", "zara", "h&m", "louisvuitton", "chanel", "gucci", "prada", "hermes", "dior", "burberry", "ralphlauren", "armani", "cartier", "versace", "loreal", "maybelline", "garnier", "nivea", "dove", "gillette", "pantene", "colgate", "oralb", "philips", "bosch", "siemens", "lenovo", "dell", "hp", "acer", "asus", "logitech", "razer", "epicgames", "ea", "ubisoft", "activision", "nintendo", "playstation", "xbox", "tesco", "walmart", "carrefour", "aldi", "lidl", "ikea", "decathlon", "woolworths", "sainsburys", "target", "costco", "sephora", "mac", "esteeLauder", "urbanDecay", "nyx", "tooFaced", "benefit", "tarte", "kylieCosmetics", "fentyBeauty", "patMcGrath", "anastasiaBeverlyHills", "morphe", "hourglass", "glossier", "hudaBeauty", "nars", "clinique"],
        'weather_terms' => ["soleil", "pluie", "vent", "neige", "orage", "nuage", "hiver", "été", "printemps", "automne", "canicule", "déluge", "cyclone", "tornade", "tsunami", "tempête", "brume", "humidité", "arcenciel", "givre", "éclair", "grêle", "gel", "vague", "marée", "brise", "ouragan", "ciel", "foudre", "tourbillon", "mistral", "brouillard", "averse", "rosée", "inondation", "sécheresse", "typhon", "bourrasque", "rafale", "glace", "givré", "cumulus", "stratus", "nimbus", "anticyclone", "dépression", "courant", "chaleur", "fraîcheur", "dégel", "zéphyr", "souffle", "alizé", "nord", "sud", "est", "ouest", "crépuscule", "aurore", "lumière", "obscurité", "équinoxe", "solstice", "coucher", "lever", "météore", "phénomène", "tornade", "tourmente", "monsoon", "dérive", "glissement", "aval", "crue", "érosion", "dérèglement", "pollution", "atmosphère", "ozone", "nuit", "jour", "douche", "flocon", "neigeux", "frimas", "sirocco", "bourgeon", "gelée", "tempétueux", "cendré", "clair", "mauvais", "météo", "saison", "températures", "précipitations", "orages"],
        'close_relations' => ["Lucas", "Emma", "Hugo", "Clara", "Nathan", "Lola", "Émilie", "Antoine", "Camille", "Léa", "Paul", "Charlotte", "Gabriel", "Alice", "Louis", "Manon", "Maxime", "Sarah", "Théo", "Élise", "Julien", "Marie", "Thomas", "Éva", "Alexandre", "Chloé", "Victor", "Arthur", "Raphaël", "Noé", "Éléonore", "Lucie", "Adrien", "Aurélie", "Amélie", "Sophie", "Léonie", "Alix", "Estelle", "Mathilde", "Louise", "Jules", "Thibault", "Pierre", "Quentin", "Nicolas", "Cécile", "Florent", "Valentin", "Zoé", "Anna", "Angèle", "Olivier", "Baptiste", "Catherine", "Jean", "François", "Sébastien", "Michel", "Agnès", "Jacques", "Isabelle", "Didier", "Mathieu", "Patrick", "Sophie", "Vincent", "Clémence", "Élodie", "Marc", "Hélène", "Christine", "Arnaud", "Coralie", "Philippe", "Claire", "Georges", "Henri", "Dominique", "André", "Laure", "Lilian", "Gilles", "Colette", "Bernard", "Danielle", "Pauline", "Frédéric", "Karine", "Monique", "Jean-Pierre", "Michel-Ange", "Annick", "Béatrice", "Marie-France", "Stéphane", "Hervé"],
        'important_events' => ["Mariage2023", "Noël2023", "Anniversaire01", "Vacances2024", "Pâques", "NouvelAn2023", "SaintValentin", "Halloween", "DépartRetraite", "FêteDesMères", "Naissance", "Pacs2022", "Voyage2020", "PremierBebe", "Crémaillère", "Baptême", "Communion", "RentréeScolaire", "Réunion", "Déménagement", "FêteDesPères", "MariageCivil", "Cérémonie", "AnniversaireSurprise", "VoyageDeNoces", "AnniversaireDeMariage", "RéveillonNoël", "RéveillonNouvelAn", "SoiréeHalloween", "RetourDeVacances", "ExamenFinal", "JourDiplôme", "InscriptionUniversité", "FêteDesGrandsParents", "ReunionFamiliale", "NaissancePetitEnfant", "CélébrationAnniversaire", "VoyageEntreAmis", "MariageAmi", "BabyShower", "EnterrementVieDeJeuneFille", "EnterrementVieDeGarçon", "AnniversaireCollègue", "PromotionProfessionnelle", "PotDeDépart", "PotDAccueil", "Conférence", "Séminaire", "Atelier", "SalonProfessionnel", "LancementDeProduit", "FêteDeQuartier", "BarbecueEntreAmis", "FêteNationale", "VictoireSportive", "MatchImportant", "CompétitionLocale", "RencontreSportive", "TournoiEchecs", "ConcoursPhotographie", "FestivalMusique", "FestivalCinéma", "JournéeDeLaTerre", "MarathonVille", "JournéePortesOuvertes", "RassemblementMoto", "ExpositionArt", "FêteDesVoisins", "TournoiGaming", "SoiréeJeux", "Kermesse", "GalaDeCharité", "DînerDeBienfaisance", "Inauguration", "FêteDeLaScience", "LancementCampagne", "SoiréeDeGala", "BalDesPompiers", "BrocanteDeQuartier", "RencontreCultural", "AnniversaireEntreprise", "JournéeDIntegration", "SortieScolaire", "RencontreAlumni", "RemiseDePrix", "FêteFinAnnée", "ConférenceMotivationnelle", "SoiréeCaritative", "AssembléeGénérale", "RéunionAnnuelle", "FêteDePrintemps", "FestivalDeThéâtre", "SpectacleDanse", "ConcertClassique"],
        'affectionate_terms' => ["amour", "doudou", "chéri", "bébé", "moncoeur", "passion", "câlin", "bisous", "douceur", "tendresse", "ange", "poupée", "étoile", "honey", "honey123", "darling", "mylove", "mybaby", "sweetheart", "sugar", "snuggle", "snugglebug", "babyboo", "cutie", "cutiepie", "lovedove", "lovebug", "huggie", "huggiebear", "pumpkin", "sweetpea", "honeybear", "lovebird", "peach", "muffin", "cupcake", "dear", "dearest", "cherished", "beloved", "honeybun", "sunshine", "darlingheart", "kissy", "kissyface", "sweety", "sweetiepie", "babycakes", "sugarpie", "angelbaby", "lamb", "lambchop", "treasure", "joy", "light", "angelheart", "precious", "babe", "honeybunch", "loveheart", "petal", "rosy", "shiningstar", "snugglepie", "cuddlebug", "cuddlepie", "dovey", "kitten", "kitty", "lovey", "loveydove", "pumpkinpie", "smiley", "teddy", "teddybear", "buttercup", "dearie", "dumpling", "giggles", "honeybunny", "kisses", "littleone", "pookie", "sweetiekins", "babydoll", "cherie", "moncheri", "lapin", "choupinou", "bijou", "coeur"],
        'specific_places' => ["Eiffel", "MontSaintMichel", "PontNeuf", "ChampsElysees", "NotreDame", "Disneyland", "Trocadéro", "Pyramides", "Versailles", "Louvre", "SacréCoeur", "Invalides", "Croisette", "GorgesVerdon", "Château", "SaintTropez", "BigBen", "Colisée", "TajMahal", "MachuPicchu", "Stonehenge", "Kremlin", "Acropole", "Sphinx", "AngkorWat", "GoldenGate", "EmpireState", "MountRushmore", "BurjKhalifa", "PetronasTowers", "SydneyOpera", "ChristRedeemer", "GreatWall", "NiagaraFalls", "GrandCanyon", "Yellowstone", "Alcatraz", "Hollywood", "TimesSquare", "CentralPark", "BrooklynBridge", "WallStreet", "MadisonSquare", "Broadway", "WhiteHouse", "Pentagon", "Capitol", "Smithsonian", "Metropolitan", "GettyCenter", "BostonCommon", "Harvard", "MIT", "Stanford", "Berkeley", "SiliconValley", "SpaceNeedle", "MountRainier", "Yosemite", "Sequoia", "DeathValley", "Zion", "BryceCanyon", "Arches", "RockyMountain", "Glacier", "Denali", "Everglades", "SmokyMountains", "BlueRidge", "MesaVerde", "Acadia", "Badlands", "Haleakalā", "CraterLake", "CarlsbadCaverns", "YellowstoneLake", "OldFaithful", "JacksonHole", "Aspen", "Vail", "Telluride", "ParkCity", "LakeTahoe", "MountWhitney", "JoshuaTree", "Mojave", "BigSur", "MontereyBay", "PebbleBeach", "GoldenGatePark", "FishermanWharf", "CableCars", "ChinatownSF", "UnionSquare", "AlamoSquare", "CoitTower", "LombardStreet", "FortPoint", "MissionDolores"],
        'international_words' => [
            "hello", "password", "welcome", "sunshine", "love", "baby", "admin", "manager", "tester", "root", "default", "user", "success", "winner", "team", "sky", "blue", "ocean", "star", "rainbow",
            "world", "freedom", "future", "peace", "hope", "global", "unity", "friendship", "happiness", "dream", "goal", "vision", "justice", "planet", "humanity", "compassion", "charity", "growth",
            "education", "progress", "innovation", "technology", "communication", "trust", "value", "effort", "kindness", "nature", "health", "care", "smile", "joy", "strength", "power", "energy",
            "light", "infinity", "balance", "beauty", "truth", "dignity", "wisdom", "respect", "integrity", "honor", "diversity", "unity", "equality", "liberty", "solidarity", "partnership", "collaboration",
            "faith", "courage", "loyalty", "determination", "inspiration", "adventure", "curiosity", "creativity", "passion", "excellence", "leadership", "action", "movement", "service", "support", "protection",
            "knowledge", "skill", "talent", "potential", "opportunity", "choice", "change", "experience", "memory", "legacy"
        ],
        'sports_and_teams' => ["psg", "om13", "barca", "real", "arsenal", "chelsea", "bayern", "nba2023", "rolandgarros", "tourdefrance", "f1", "motoGP", "rugby15", "allblacks", "sixnations", "olympics", "championsleague", "coupe2023", "euro2024", "manutd", "liverpool", "juventus", "inter", "milan", "atletico", "dortmund", "shakhtar", "ajax", "galatasaray", "boca", "river", "flamengo", "corinthians", "palmeiras", "cruzeiro", "santos", "pachuca", "tigres", "monterrey", "clubamerica", "laGalaxy", "newyorkredbulls", "seattlesounders", "torontofc", "vancouver", "celtic", "rangers", "psv", "feyenoord", "porto", "benfica", "sporting", "cska", "spartak", "zenit", "besiktas", "fenerbahce", "anderlecht", "genk", "brugge", "stuttgart", "schalke", "hertha", "hamburg", "monaco", "lyon", "marseille", "nantes", "rennes", "lens", "saintetienne", "nice", "toulouse", "montpellier", "brest", "lorient", "angers", "reims", "strasbourg", "metz", "bordeaux", "tours", "caen", "havre", "guingamp", "sochaux", "auxerre", "dijon", "troyes", "ajaccio", "bastia", "nancy", "amiens", "clermont", "valenciennes", "niort", "chateauroux", "creteil", "parisfc"]
    ];

    /**
     * @var array Errors encountered during validation.
     */
    private array $errors = [];

    public function validate(string $password): bool
    {
        $this->flushErrors();
        foreach ($this->weakPasswords as $category => $passwords) {
            if (in_array(strtolower($password), $passwords, true)) {
                $this->errors[] = $this->generateErrorMessage($category, $password);
            }
        }
        return empty($this->errors);
    }

    public function getEncounteredErrors(): array
    {
        return $this->errors;
    }

    public function flushErrors(): void
    {
        $this->errors = [];
    }

    private function generateErrorMessage(string $category, string $password): string
    {
        return match ($category) {
            'cities' => "Le mot de passe '$password' est trop facile car il correspond au nom d'une ville.",
            'departments' => "Le mot de passe '$password' est trop facile car il correspond à un numéro de département.",
            'birthdates' => "Le mot de passe '$password' est trop facile car il ressemble à une date de naissance.",
            'names' => "Le mot de passe '$password' est trop facile car il correspond à un prénom ou un nom.",
            'pets' => "Le mot de passe '$password' est trop facile car il correspond au nom d'un animal courant.",
            'days_and_months' => "Le mot de passe '$password' est trop facile car il correspond à un jour ou un mois.",
            'keyboard_patterns' => "Le mot de passe '$password' est trop facile car il utilise un motif de clavier prévisible.",
            'hobbies' => "Le mot de passe '$password' est trop facile car il correspond à un loisir courant.",
            'celebrities' => "Le mot de passe '$password' est trop facile car il correspond à un nom de célébrité.",
            'events' => "Le mot de passe '$password' est trop facile car il correspond à un événement commun.",
            'films_and_series' => "Le mot de passe '$password' est trop facile car il correspond à un titre de film ou de série.",
            'geographical_references' => "Le mot de passe '$password' est trop facile car il correspond à une référence géographique.",
            'brands_and_companies' => "Le mot de passe '$password' est trop facile car il correspond à une marque ou une entreprise.",
            'weather_terms' => "Le mot de passe '$password' est trop facile car il correspond à un terme météorologique.",
            'close_relations' => "Le mot de passe '$password' est trop facile car il correspond à un nom d'un proche.",
            'important_events' => "Le mot de passe '$password' est trop facile car il correspond à un événement important.",
            'affectionate_terms' => "Le mot de passe '$password' est trop facile car il utilise un terme affectueux.",
            'specific_places' => "Le mot de passe '$password' est trop facile car il correspond à un lieu spécifique.",
            'phone_numbers' => "Le mot de passe '$password' est trop facile car il ressemble à un numéro de téléphone.",
            'international_words' => "Le mot de passe '$password' est trop facile car il correspond à un mot international courant.",
            'sports_and_teams' => "Le mot de passe '$password' est trop facile car il correspond à une équipe ou un sport.",
            default => "Le mot de passe '$password' est trop facile.",
        };
    }
}