<?php

namespace App\AdminBundle\SubBundles\ExportingSubBundle\Infrastructure\Symfony\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('exporting_sub_bundle');

        $treeBuilder->getRootNode()
            ->children()
            ->scalarNode('encoding')->defaultValue('utf-8')->end()
            ->arrayNode('formats')
            ->children()
            ->arrayNode('csv')
            ->children()
            ->scalarNode('delimiter')->defaultValue(';')->end()
            ->scalarNode('enclosure')->defaultValue('"')->end()
            ->scalarNode('escape_char')->defaultValue('\\')->end()
            ->end()
            ->end()
            ->arrayNode('pdf')
            ->children()
            ->scalarNode('renderer')->defaultValue('wkhtmltopdf')->end()
            ->arrayNode('storage')
            ->children()
            ->scalarNode('provider')->defaultValue('local')->end()
            ->scalarNode('bucket')->defaultValue('my-exported-files')->end()
            ->scalarNode('path')->defaultValue('exports/pdf/')->end()
            ->end()
            ->end()
            ->scalarNode('title')->defaultValue('Exported Report')->end()
            ->scalarNode('footer')->defaultValue('Generated by ExportingSubBundle')->end()
            ->arrayNode('margins')
            ->children()
            ->integerNode('top')->defaultValue(10)->end()
            ->integerNode('bottom')->defaultValue(10)->end()
            ->integerNode('left')->defaultValue(10)->end()
            ->integerNode('right')->defaultValue(10)->end()
            ->end()
            ->end()
            ->scalarNode('font')->defaultValue('Arial')->end()
            ->end()
            ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}