<?php

declare(strict_types=1);

namespace App\DataFixtures;

use Doctrine\Bundle\FixturesBundle\Fixture;
use Doctrine\Bundle\FixturesBundle\FixtureGroupInterface;
use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\DBAL\Connection;
use Doctrine\Persistence\ObjectManager;

class EnterpriseFixture extends Fixture implements FixtureGroupInterface, FixtureInterface
{
    public function __construct(private readonly Connection $conn) {}

    public static function getGroups(): array
    {
        // load with: php bin/console doctrine:fixtures:load --group=enterprises
        return ['enterprises', 'demo'];
    }

    public function load(ObjectManager $manager): void
    {
        // wipe the table (safe for dev/demo)
        $this->conn->executeStatement('DELETE FROM `enterprise`');
        $this->conn->executeStatement('ALTER TABLE `enterprise` AUTO_INCREMENT = 1');

        $rows = [
            // id is omitted to let AUTO_INCREMENT assign it
            [
                'nom'                      => 'Gamma Energies',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Gamma',
                'complement_nom'           => '1',
                'tva_intra_communautaire'  => 'FR11111111123',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100023',
                'num_telephone'            => '0610000012',
                'email_entreprise'         => 'alice.alpha@example.com',
                'nom_responsable'          => 'Alice Alpha',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'alice.alpha@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000012',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Delta IT',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Delta IT',
                'complement_nom'           => '2',
                'tva_intra_communautaire'  => 'FR11111111119',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100029',
                'num_telephone'            => '0610000020',
                'email_entreprise'         => 'alice.alpha@example.com',
                'nom_responsable'          => 'Alice Alpha',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'alice.alpha@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000020',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Entreprise A SARL',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'A',
                'complement_nom'           => '3',
                'tva_intra_communautaire'  => 'FR11111111118',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100028',
                'num_telephone'            => '0610000021',
                'email_entreprise'         => 'carla.gamma@example.com',
                'nom_responsable'          => 'Carla Gamma',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'carla.gamma@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000021',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Entreprise B SARL',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'B',
                'complement_nom'           => '4',
                'tva_intra_communautaire'  => 'FR11111111117',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100027',
                'num_telephone'            => '0610000022',
                'email_entreprise'         => 'carla.gamma@example.com',
                'nom_responsable'          => 'Carla Gamma',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'carla.gamma@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000022',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Gamma Energies',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Gamma',
                'complement_nom'           => '5',
                'tva_intra_communautaire'  => 'FR11111111125',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100033',
                'num_telephone'            => '0610000023',
                'email_entreprise'         => 'bruno.beta@example.com',
                'nom_responsable'          => 'Bruno Beta',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'bruno.beta@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000023',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Gamma Services',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Gamma Svc',
                'complement_nom'           => '6',
                'tva_intra_communautaire'  => 'FR11111111124',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100032',
                'num_telephone'            => '0610000024',
                'email_entreprise'         => 'carla.gamma@example.com',
                'nom_responsable'          => 'Carla Gamma',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'carla.gamma@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000024',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Omega Services',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Omega',
                'complement_nom'           => '7',
                'tva_intra_communautaire'  => 'FR11111111122',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100030',
                'num_telephone'            => '0610000025',
                'email_entreprise'         => 'carla.gamma@example.com',
                'nom_responsable'          => 'Carla Gamma',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'carla.gamma@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000025',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Delta Industrie SAS',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Delta Indus',
                'complement_nom'           => '8',
                'tva_intra_communautaire'  => 'FR11111111121',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100031',
                'num_telephone'            => '0610000013',
                'email_entreprise'         => 'bruno.beta@example.com',
                'nom_responsable'          => 'Bruno Beta',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'bruno.beta@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000013',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Entreprise A SARL',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'A',
                'complement_nom'           => '9',
                'tva_intra_communautaire'  => 'FR11111111120',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100024',
                'num_telephone'            => '0610000014',
                'email_entreprise'         => 'bruno.beta@example.com',
                'nom_responsable'          => 'Bruno Beta',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'bruno.beta@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000014',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Entreprise B SARL',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'B',
                'complement_nom'           => '10',
                'tva_intra_communautaire'  => 'FR11111111116',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100026',
                'num_telephone'            => '0610000015',
                'email_entreprise'         => 'alice.alpha@example.com',
                'nom_responsable'          => 'Alice Alpha',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'alice.alpha@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000015',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Delta Industrie SAS',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Delta Indus',
                'complement_nom'           => '11',
                'tva_intra_communautaire'  => 'FR11111111115',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100025',
                'num_telephone'            => '0610000016',
                'email_entreprise'         => 'bruno.beta@example.com',
                'nom_responsable'          => 'Bruno Beta',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'bruno.beta@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000016',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Entreprise A SARL',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'A',
                'complement_nom'           => '12',
                'tva_intra_communautaire'  => 'FR11111111114',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100018',
                'num_telephone'            => '0610000018',
                'email_entreprise'         => 'alice.alpha@example.com',
                'nom_responsable'          => 'Alice Alpha',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'alice.alpha@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000018',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
            [
                'nom'                      => 'Omega Services',
                'code_ape'                 => '6201Z',
                'sigle'                    => 'Omega',
                'complement_nom'           => '13',
                'tva_intra_communautaire'  => 'FR11111111112',
                'statut'                   => null,
                'type'                     => null,
                'nature'                   => null,
                'siret'                    => '11111111100020',
                'num_telephone'            => '0610000009',
                'email_entreprise'         => 'alice.alpha@example.com',
                'nom_responsable'          => 'Alice Alpha',
                'fonction_referent'        => null,
                'siren'                    => '111111111',
                'naf'                      => '6201Z',
                'nationalite'              => 'France',
                'email_referent'           => 'alice.alpha@example.com',
                'adresse_id'               => null,
                'created_at'               => '2025-10-13 17:55:49',
                'suppleant1'               => null,
                'nom_suppleant1'           => null,
                'suppleant2'               => null,
                'nom_suppleant2'           => null,
                'gratuit'                  => 0,
                'entreprise_mere_id'       => null,
                'telephone_referent'       => '0610000009',
                'telephone_suppleant1'     => null,
                'telephone_suppleant2'     => null,
            ],
        ];

        foreach ($rows as $row) {
            $this->conn->insert('enterprise', $row);
        }
    }
}
